services:
  backrest:
    image: garethgeorge/backrest:v1.14.1
    container_name: backrest
    hostname: backrest
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config:/config
      - ./cache:/cache
      - ./tmp:/tmp
      - ./rclone:/root/.config/rclone
      - ../:/userdata:ro
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=${TZ}
    ports:
      - '9898:9898'
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'